version: '3.8'

services:
  backend:
    build: ./calculative-backend
    ports:
      - "5000:5000"
    volumes:
      - ./calculative-backend/app:/app/app
    environment:
      - FLASK_ENV=development

  oldweb:
    build: ./calculative-oldweb
    ports:
      - "8080:80"
    volumes:
      - ./calculative-oldweb/src:/usr/share/nginx/html:ro

  web:
    build: ./calculative-web
    ports:
      - "3000:3000"
    volumes:
      - ./calculative-web/src:/app/src
    command: ["npm", "run", "dev"]